Repository TimeYourTask/Tyta-cors, pull requests merged in 2022-11, with the labels that each got.

#1 feat(TYTA-21/TYTA-22): Implement basic nodejs server with express
  .env.exemple
  .gitignore
  package.json
  src/server.js
Labels: PR - Review OK

#2 feat(TYTA-23) : Add Mongoose to connect to mongoDB cluster & expressJson
  package.json
  src/server.js
Labels: PR - Review OK

#4 feat(TYTA-58) : add Readme
  README.md
Labels: PR - Review TO DO

#3 story/TYTA-7/dockerize-backend-application
  .env.sample
  docker-compose.yml
  package.json
  src/server.js
Labels: PR - Review OK, effort: small

#6 story/TYTA-41/create-project-model
  docs/Tyta.postman_collection.json
  package.json
  src/controllers/userCtrl.js
  src/models/userModel.js
  src/routes/userRoute.js
  src/server.js
Labels: PR - Review OK

#10 feat(TYTA-48): setup nodemailer (with MDS emails)
  .env.sample
  package.json
  src/utils/nodemailer.js
Labels: PR - Review OK

#11 feat(User): Add authentification method in controller user and JWT
  .env.sample
  package.json
  src/controllers/userCtrl.js
  src/models/userModel.js
  src/routes/userRoute.js
Labels: PR - Review OK

#7 feat(TYTA-37): add team model
  src/models/teamModel.js
Labels: PR - Review OK

#8 feat(TYTA-39): add team controller
  src/controllers/teamCtrl.js
Labels: PR - Review OK

#9 feat(TYTA-38): add team routes
  docs/Tyta.postman_collection.json
  src/routes/teamRoute.js
  src/server.js
Labels: PR - Review OK

#17 bug/TYTA-119/persistent-mongodb-database
  .gitignore
  docker-compose.yml
Labels: PR - Review OK

#16 bug/TYTA-107/app-crash-if-authentification-failed
  src/controllers/userCtrl.js
Labels: PR - Review TO DO
