Repository TimeYourTask/Tyta-cors, pull requests merged in 2022-12, with the labels that each got.

#12 story/TYTA-41/setup-project-model
  src/models/projectModel.js
Labels: PR - Review TO DO

#14 story/TYTA-42/setup-route-for-project-methods
  src/routes/projectRoute.js
  src/server.js
Labels: PR - Review TO DO

#13 Story/tyta 43/create-project-controller
  src/controllers/projectCtrl.js
Labels: PR - Review TO DO

#18 Story/tyta 27/implement testing library
  .env.sample
  .gitignore
  __tests__/server.tests.js
  package-lock.json
  package.json
  src/app.js
  src/server.js
Labels: PR - Review OK

#21 hotfix: missing requirements
  package-lock.json
  src/server.js
Labels: PR - Review OK

#23 Story/tyta 49/confirm user creating with email
  src/controllers/userCtrl.js
  src/utils/nodemailer.js
Labels: PR - Review OK

#19 story/TYTA-44/create-task-model
  src/controllers/taskCtrl.js
  src/models/taskModel.js
  src/routes/projectRoute.js
  src/routes/taskRoute.js
  src/server.js
Labels: PR - Review OK

#26 bug/TYTA-120/unexpected-result-on-update-project
  src/controllers/projectCtrl.js
Labels: PR - Review OK

#27 bug/TYTA-121/unexpected-message-on-delete-project
  src/controllers/projectCtrl.js
Labels: PR - Review OK, effort: small

#24 story/TYTA-124/create-reset-password-feature
  .env.sample
  .eslintrc.json
  docs/Tyta.postman_collection.json
  package.json
  src/controllers/userCtrl.js
  src/models/teamModel.js
  src/models/tokenModel.js
  src/routes/authRoute.js
  src/routes/userRoute.js
  src/server.js
Labels: PR - Review TO DO, Question

#30 Refacto/tyta/changes in controller
  .gitignore
  src/controllers/projectCtrl.js
  src/controllers/teamCtrl.js
  src/controllers/userCtrl.js
  src/middleware/authMiddleware.js
  src/models/teamModel.js
  src/routes/teamRoute.js
  src/routes/userRoute.js
Labels: PR - Review OK

#31 story/TYTA-114/add-view-for-creating-project
  src/controllers/projectCtrl.js
  src/controllers/teamCtrl.js
  src/controllers/userCtrl.js
  src/models/projectModel.js
  src/models/taskModel.js
  src/routes/projectRoute.js
  src/routes/teamRoute.js
Labels: PR - Review TO DO

#32 add email templates for welcome and reset password
  src/controllers/projectCtrl.js
  src/controllers/teamCtrl.js
  src/controllers/userCtrl.js
  src/utils/mails.js
  src/utils/nodemailer.js
Labels: PR - Review OK

#33 add-ci-to-check-eslint-rules
  .eslintrc.json
  .github/workflows/eslint.yml
  __tests__/server.tests.js
  package.json
  src/app.js
  src/controllers/teamCtrl.js
  src/controllers/userCtrl.js
  src/models/projectModel.js
  src/routes/userRoute.js
Labels: PR - Review OK

#29 story/TYTA-84/create-task-time-model
  .env.sample
  .eslintrc.json
  package.json
  src/controllers/taskCtrl.js
  src/controllers/teamCtrl.js
  src/controllers/timeTaskCtrl.js
  src/middleware/verifyTaskIdParams.js
  src/models/taskModel.js
  src/models/timeTaskModel.js
  src/routes/taskRoute.js
  src/routes/timeTaskRoute.js
  src/server.js
Labels: PR - Review TO DO

#34 Story/tyta 26/add and configure swagger
  package.json
  src/docs/swagger.js
  src/server.js
Labels: PR - Review OK
