Repository TimeYourTask/Tyta-cors, pull requests merged in 2023-01, with the labels that each got.

#35 story/TYTA-53/task-listing
  src/controllers/taskCtrl.js
  src/controllers/userCtrl.js
Labels: PR - Review TO DO

#37 fix: remove __v from results
  package.json
  src/models/projectModel.js
  src/models/taskModel.js
  src/models/teamModel.js
  src/models/tokenModel.js
  src/models/userModel.js
Labels: PR - Review TO DO, effort: small

#36 TASK/TYTA-134/get user of the team in project and task
  src/controllers/projectCtrl.js
  src/controllers/teamCtrl.js
  src/docs/swagger.js
  src/routes/projectRoute.js
  src/routes/teamRoute.js
Labels: PR - Review TO DO

#39 story/TYTA-53/update-overview-page
  src/controllers/timeTaskCtrl.js
Labels: PR - Review OK

#40 Add function to get user tasks
  src/controllers/taskCtrl.js
  src/routes/taskRoute.js
Labels: PR - Review OK, effort: small

#41 story/TYTA-98/securize-critical-backend-routes
  src/config/global.js
  src/controllers/teamCtrl.js
  src/controllers/userCtrl.js
  src/docs/swagger.js
  src/middleware/auth.middleware.js
  src/middleware/authorization.middleware.js
  src/models/userModel.js
  src/routes/projectRoute.js
  src/routes/taskRoute.js
  src/routes/teamRoute.js
  src/routes/timeTaskRoute.js
  src/routes/userRoute.js
Labels: PR - Review OK, Security

#42 story/TYTA-99/securize-edit-and-delete-scope-of-users
  src/controllers/projectCtrl.js
  src/controllers/taskCtrl.js
  src/controllers/teamCtrl.js
  src/docs/swagger.js
  src/models/projectModel.js
  src/models/taskModel.js
  src/models/teamModel.js
  src/routes/taskRoute.js
Labels: PR - WIP
